spring.application.name=SmartHospitalManagementSystem

spring.datasource.url=${mysql://root:spALuordqhaGDcgqUZnMOAvpwHrQDRhk@mysql.railway.internal:3306/railway}
spring.datasource.username=${root}
spring.datasource.password=${spALuordqhaGDcgqUZnMOAvpwHrQDRhk}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=${PORT:8181}


#spring.application.name=SmartHospitalManagementSystem
#
#spring.datasource.url=jdbc:mysql://zephyr.proxy.rlwy.net:33661/railway
#spring.datasource.username=root
#spring.datasource.password=spALuordqhaGDcgqUZnMOAvpwHrQDRhk
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#
#server.port=8181
#

#
#spring.application.name=SmartHospitalManagementSystem
#
#spring.datasource.url=jdbc:mysql://localhost:3306/SmartHospitalManagement
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#server.port=8181