spring.application.name=HospitalManagementProj

#db configuration

spring.datasource.driver-class-name=oracle.driver.OracleDriver
spring.datasource.username=system
spring.datacourse.password=2045


spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.format_sql=true //Format the hibernate queries, statements